### ISSUE TITLE
Version::__toString()

### ISSUE THREAD

**Issue by aderuwe** [kherge-archive/php-version#2]
I feel it would be beneficial to implement `__toString()` in Version, and to call that in `Dumper::toString()` - reason being I don't really want to care about displaying version numbers, I would just like to be able to `echo new Version(1, 0, 0);`.

Would this be acceptable? I'll gladly provide a PR. Thanks.

**Comment by ghost** [comment]
I think this would be a nice addition!

A PR would be appreciated.
