### ISSUE TITLE
robustness of reading a version tag

### ISSUE THREAD

**Issue by cordoval** [kherge-archive/php-version#6]
can we make the  toBuilder more robust?

``` php
$builder = Parser::toBuilder($lastTag);
```

``` bash
  [Herrera\Version\Exception\InvalidStringRepresentationException]
  The version string representation "v1.0.0" is invalid.
```

**Comment by ghost** [comment]
Hmm, this is a tough call.

This library tries to be very strict with the [Semantic Versioning](http://semver.org/spec/v2.0.0.html) specifications, and prefixing version numbers with "v" is not part of the spec. In fact, [there was a tiny mention about it](https://github.com/mojombo/semver/issues/32#issuecomment-7181759).

I know that it is probably trivial, but my feeling is that I don't want to support it.

Something people can use is:

``` php
$builder = Parser::toBuilder(ltrim($lastTag, 'v'));
```

And if it's something that is frequently used in a library, the class can be extended to support the "v" prefix:

``` php
use Herrera\Version\Parser as Base

class Parser extends Base
{
    public static function toBuilder($version)
    {
        return parent::toBuilder(ltrim($version, 'v'));
    }
}
```

**Comment by cordoval** [comment]
I solved it as you can see in Gush PR, yeah Gush is using php-version :baby: 
my use case was as in the PR since when I tag or shown also on the git book one does `git tag -a v1.0.0 -m "text here"`

anyway closing, good to have your thoughts on this
